version: "3.7"

volumes:
  grafana-data:
  prometheus-data:

services:
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring  # Conectar a la red personalizada

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      - '--web.enable-lifecycle'
    networks:
      - monitoring  # Conectar a la red personalizada

  app_example:
    image: quay.io/brancz/prometheus-example-app:v0.3.0
    container_name: app_example
    restart: unless-stopped
    ports:
      - 8081:8080 # Expuesto en 8081 para NGINX
    networks:
      - monitoring  # Conectar a la red personalizada

  app_example2:
    image: quay.io/brancz/prometheus-example-app:v0.3.0
    container_name: app_example2
    restart: unless-stopped
    ports:
      - 8082:8080 # Expuesto en 8082 para NGINX
    networks:
      - monitoring  # Conectar a la red personalizada

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80 # Balanceador de carga accesible en el puerto 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Archivo de configuración para NGINX
    networks:
      - monitoring  # Conectar a la red personalizada

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: unless-stopped
    ports:
      - 9113:9113  # Puerto para el exportador de NGINX
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite acceder a las métricas de NGINX
    command:
      - '--nginx.scrape-uri=http://nginx:80/stub_status'  # Configurar el URI de scrape aquí
    networks:
      - monitoring  # Conectar a la red personalizada


networks:
  monitoring:  # Red personalizada para los servicios
      driver: bridge